### ISSUE TITLE
TypeError: Invalid type

### ISSUE THREAD

**Issue by spcfox** [translate-tools/linguist#506]
## Description
Sometimes the translation ends with an error:
```plaintext
Uncaught (in promise) TypeError: Invalid type
    at yr (contentscript.js:2:313244)
    at contentscript.js:2:316449
```

## Configuration
Sent to email linguist-support@vitonsky.net

## Environment
Linguist version: 6.0.1
Browser: Brave
Browser version: 1.68.137
Chromium: 127.0.6533.100

**Comment by vitonsky** [comment]
@spcfox i did not received email with config, could you send again to support@linguister.io

The config are essential, to debug your problem

**Comment by spcfox** [comment]
@vitonsky Done
